### ISSUE TITLE
fix: use hook does't set isLoading to false when invalid doc id passed

### ISSUE THREAD

**Issue by LeandroTorresSicilia** [reiniergs/firestore-ts-client-builder#38]
when passing an invalid doc id that does not exists in the DB then the query fails and the loading state does not get updated to false, and instead stuck in `true` forever

**Comment by LeandroTorresSicilia** [comment]
also isLoading should be true by default

**Comment by HellWolf93** [comment]
> also isLoading should be true by default

i don't think this will be ok, because if we pass `disabled = true` then `isLoading` will be true, which is incorrect

**Comment by LeandroTorresSicilia** [comment]
> 

yes you are right but what we can do is to set initial isLoading state to `!disabled` because when you use it without pass disabled and you want to fetch data from start, if the isLoading is false initially then at start data will be undefined and isLoading false, and there are time when you need to do something like:

```
if (!data && !isLoading) {
    navigate('/')
}
```

What that means to me is that when there is no data and is is not loading which means that the hook finish to do its job then if there is no data then redirect to another page, that can happens for example when put an invalid id resource in the URL
