### ISSUE TITLE
feat: add errors to hooks

### ISSUE THREAD

**Issue by HellWolf93** [reiniergs/firestore-ts-client-builder#41]
### Description:

Right now our hooks return an object with `data` and `isLoading` properties. When an error occurs, there is no way to know what happened from the user side, and therefore no way to gracefully handle those errors.

### Proposal:
We should add a new propertie to the response of the hooks, `error`, that will contain information about what happened so the user can handle it.

### To discuss:

What type should the error be? Maybe we could just expose the `FirestoreError` since the only think we are doing is requesting data from Firestore.

### Example usage

```ts
import useCustomer from '~/data/customer/use';

const CustomerDetails = () => {
    const { data, error, isLoading } = useCustomer('incorrect-docid');

    if (isLoading) {
        return <div>Loading...</div>;
    }

    if (error) {
        return <div>Something went wrong: {{ error.message }}</div>;
    }

    return (
        <div>
            <h1>{data.name}</h1>
        </div>
    );
};

export default CustomerDetails;
```

**Comment by reiniergs** [comment]
@HellWolf93 this issue is fix in #43 , right? if so, please close the issue
